---
- name: Deploy Backend
  hosts: gcp_manager_sam
  vars_files:
    - environments/all.yml
    - environments/{{ env }}/vars.yml
    - environments/{{ env }}/vault

  roles:
    - role: immersio-backend
      stack_name: "{{ env }}-immersio-backend"
      dest_folder: "/apps" 
      hostname: "{{ backend_app_hostname }}"
    
    - role: immersio-frontend
      stack_name: "{{ env }}-immersio-frontend"
      dest_folder: "/apps" 
      hostname: "{{ front_app_hostname }}"

    - role: immersio-admin
      stack_name: "{{ env }}-immersio-admin"
      dest_folder: "/apps" 
      hostname: "{{ admin_app_hostname }}"
     


