

build:
	docker compose -f local.yml up --build -d --remove-orphans

down:
	docker compose -f local.yml down -v

config:
	docker compose -f local.yml config 
 

up:
	docker compose -f local.yml up -d
 


